# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
